version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
      timezone: "UTC"
    open-pull-requests-limit: 5
    versioning-strategy: increase
    commit-message:
      prefix: "chore(deps)"
    ignore:
      - dependency-name: "@nestjs/*"
        update-types: ["version-update:semver-major"]
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:15"
      timezone: "UTC"
    commit-message:
      prefix: "chore(actions)"
