name: Commitlint

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  commitlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: pnpm/action-setup@v4
        with:
          version: 9.6.0
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm
      - run: pnpm i --frozen-lockfile
      - name: Run commitlint
        env:
          EVENT_NAME: ${{ github.event_name }}
          PR_BASE: ${{ github.event.pull_request.base.sha }}
          PR_HEAD: ${{ github.event.pull_request.head.sha }}
          PUSH_BEFORE: ${{ github.event.before }}
          PUSH_AFTER: ${{ github.sha }}
        run: |
          pnpm dlx commitlint --version
          if [ "$EVENT_NAME" = "pull_request" ]; then
            FROM="$PR_BASE"; TO="$PR_HEAD"
          else
            FROM="$PUSH_BEFORE"; TO="$PUSH_AFTER"
          fi
          echo "Checking range: $FROM..$TO"
          pnpm dlx commitlint --from "$FROM" --to "$TO"
